language: node_js
node_js:
  - 12

services:
  - docker

# Build section
script:
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  
# Tagging section
  - docker tag udagram-api-feed karimelhelw/udagram-api-feed:v1
  - docker tag udagram-api-user karimelhelw/udagram-api-user:v1
  - docker tag udagram-frontend karimelhelw/udagram-frontend:v1 
  - docker tag udagram-reverseproxy karimelhelw/udagram-reverseproxy:v1
  
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push YOUR_DOCKER_HUB/simple-node
  
# Push
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push karimelhelw/udagram-api-feed:v1
- docker push karimelhelw/udagram-api-user:v1
- docker push karimelhelw/udagram-frontend:v1
- docker push karimelhelw/udagram-reverseproxy:v1

 