apiVersion: v1
kind: Secret

metadata:
  name: aws-secret2
  namespace: default

data:
  aws_access_key_id: QUtJQVEzTVM2TUFJUTNTQTdNRzY=
  aws_secret_access_key: R3drZUV4STkzenFtaG9JeWJ3STJpeVdwK0J3Tld1NlBoa1F1VEhncg==